#docker-compose.yaml
version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg14 
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
#run docker-compose up
